package com.mycompany.wordtype;

import service.AuthService;
import java.util.function.Consumer;

import model.User;
import service.AuthResult;

public class login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());
    private final AuthService authService = new AuthService();
    private final javax.swing.JLabel lblMessage = new javax.swing.JLabel(" ");
    private Consumer<User> onLoginSuccess;
    private Runnable onRegisterClick;

    /**
     * Creates new form MainFrame
     */
    public login() {

        com.formdev.flatlaf.FlatLightLaf.setup();

        initComponents();
        // เซ็ต font
        lblMessage.setFont(new java.awt.Font("Roboto Mono", java.awt.Font.PLAIN, 13));
        jLabel1.setFont(new java.awt.Font("Space Grotesk Medium", java.awt.Font.PLAIN, 32));
        jLabel2.setFont(new java.awt.Font("Space Grotesk Medium", java.awt.Font.PLAIN, 32));
        txtPassword.setEchoChar((char) 0);

        txtUsername.putClientProperty("FlatLaf.style", "arc: 25");
        txtUsername.putClientProperty("JTextField.placeholderText", " username");

        txtPassword.setEchoChar('*');
        txtPassword.putClientProperty("FlatLaf.style", "arc: 25");
        txtPassword.putClientProperty("JTextField.placeholderText", " password");

        // 3. ปรับขอบมนให้ปุ่ม Sign in (ตรวจสอบชื่อตัวแปรปุ่มให้ตรง เช่น jButton1)
        jButton1.putClientProperty("FlatLaf.style", "arc: 25");

        this.requestFocusInWindow();

        btnUser.setForeground(new java.awt.Color(128, 128, 128));
        // 2. คำสั่งเปลี่ยนสีตัวหนังสือตอนเอาเมาส์ไปชี้
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // ตอนเอาเมาส์ไปชี้: ให้คำว่า Login เปลี่ยนเป็น "สีดำเข้ม"
                btnUser.setForeground(new java.awt.Color(0, 0, 0));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                // ตอนเอาเมาส์ออก: ให้คำว่า Login กลับไปเป็น "สีเทา" เหมือนเดิม
                btnUser.setForeground(new java.awt.Color(128, 128, 128));
            }
        });
    }

    public javax.swing.JPanel getRootPanel() {
        return jPanel1;
    }

    public void setOnLoginSuccess(Consumer<User> onLoginSuccess) {
        this.onLoginSuccess = onLoginSuccess;
    }

    public void setOnRegisterClick(Runnable onRegisterClick) {
        this.onRegisterClick = onRegisterClick;
    }

    public void showMessage(String text, boolean isError) {
        lblMessage.setForeground(isError ? new java.awt.Color(200, 50, 50) : new java.awt.Color(0, 102, 100));
        lblMessage.setText(text);
    }

    public void reset() {
        txtUsername.setText("");
        txtPassword.setText("");
        showMessage(" ", false);
        javax.swing.SwingUtilities.invokeLater(() -> txtUsername.requestFocusInWindow());
    }

    public void doLogin() {
        AuthResult result = authService.login(txtUsername.getText(), new String(txtPassword.getPassword()));

        if (!result.isSuccess()) {
            showMessage(result.getMessage(), true);
            txtPassword.setText("");
            txtPassword.requestFocusInWindow();
            return; // login ไม่สำเร็จ -> ห้ามส่ง user (null) ไปต่อ
        }
        if (onLoginSuccess != null)
            onLoginSuccess.accept(result.getUser());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLeader = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jComboBox1.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(225, 225, 227));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Space Grotesk Medium", 0, 32)); // NOI18N
        jLabel1.setText(">_word");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 36, 191, 41);

        jLabel2.setFont(new java.awt.Font("Space Grotesk Medium", 0, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 100));
        jLabel2.setText("type");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 36, 191, 41);

        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setBounds(440, 231, 320, 20);
        jPanel1.add(lblMessage);

        btnLeader.setForeground(new java.awt.Color(142, 144, 148));
        btnLeader.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/wordtype/images/LeaderIcon_OFF.png"))); // NOI18N
        btnLeader.setBorderPainted(false);
        btnLeader.setContentAreaFilled(false);
        btnLeader.setFocusPainted(false);
        btnLeader.setRolloverIcon(
                new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/wordtype/images/LeaderIcon_ON.png"))); // NOI18N
        jPanel1.add(btnLeader);
        btnLeader.setBounds(898, 52, 18, 19);

        btnUser.setFont(new java.awt.Font("Roboto Mono", 0, 16)); // NOI18N
        btnUser.setForeground(new java.awt.Color(142, 144, 148));
        btnUser.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/wordtype/images/userIcon.png"))); // NOI18N
        btnUser.setText("Login");
        btnUser.setBorderPainted(false);
        btnUser.setContentAreaFilled(false);
        btnUser.setFocusPainted(false);
        btnUser.setIconTextGap(8);
        btnUser.setRolloverIcon(
                new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/wordtype/images/userIcon_hover.png"))); // NOI18N
        btnUser.addActionListener(this::btnUserActionPerformed);
        jPanel1.add(btnUser);
        btnUser.setBounds(920, 48, 110, 28);

        jLabel3.setFont(new java.awt.Font("Roboto Mono", 1, 22)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/wordtype/images/Vector.png"))); // NOI18N
        jLabel3.setText("Sign in");
        jLabel3.setIconTextGap(12);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(535, 198, 131, 31);

        txtUsername.setBackground(new java.awt.Color(209, 211, 216));
        txtUsername.setFont(new java.awt.Font("Roboto Mono Medium", 0, 15)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(142, 144, 148));
        txtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        txtUsername.addActionListener(this::txtUsernameActionPerformed);
        jPanel1.add(txtUsername);
        txtUsername.setBounds(440, 255, 320, 44);

        txtPassword.setBackground(new java.awt.Color(209, 211, 216));
        txtPassword.setFont(new java.awt.Font("Roboto Mono Medium", 0, 15)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(142, 144, 148));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addActionListener(this::txtPasswordActionPerformed);
        jPanel1.add(txtPassword);
        txtPassword.setBounds(440, 315, 320, 44);

        jButton1.setBackground(new java.awt.Color(0, 102, 100));
        jButton1.setFont(new java.awt.Font("Roboto Mono", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign in");
        jButton1.setToolTipText("");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);
        jButton1.setBounds(440, 385, 320, 44);

        jButton2.setBackground(new java.awt.Color(225, 225, 227));
        jButton2.setFont(new java.awt.Font("Roboto Mono", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(142, 144, 148));
        jButton2.setText("create an account");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }

            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2);
        jButton2.setBounds(510, 450, 200, 28);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 700);

        setSize(new java.awt.Dimension(1200, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        System.out.println("Hhh");
    }// GEN-LAST:event_btnUserActionPerformed

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtUsernameFocusGained
        // TODO add your handling code here:

    }// GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
        txtPassword.requestFocusInWindow();
    }// GEN-LAST:event_txtUsernameActionPerformed

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtUsernameFocusLost
        // TODO add your handling code here:

    }// GEN-LAST:event_txtUsernameFocusLost

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
        doLogin();
    }// GEN-LAST:event_txtPasswordActionPerformed

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtPasswordFocusGained

    }// GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtPasswordFocusLost
        // TODO add your handling code here:

    }// GEN-LAST:event_txtPasswordFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        doLogin();
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (onRegisterClick != null)
            onRegisterClick.run();
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setForeground(java.awt.Color.BLACK);
    }// GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jButton2.setForeground(java.awt.Color.BLACK);
        jButton2.setForeground(new java.awt.Color(128, 128, 128));
    }// GEN-LAST:event_jButton2MouseExited

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        jButton2.setForeground(java.awt.Color.WHITE);
    }// GEN-LAST:event_jButton2MousePressed

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton2MouseReleased
        // TODO add your handling code here:
        jButton2.setForeground(java.awt.Color.BLACK);
    }// GEN-LAST:event_jButton2MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeader;
    private javax.swing.JButton btnUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}